BASE_URL = "http://200.152.38.155/CNPJ/"

PATH_ZIP_DIRECTORY = "datasets/raw/zip"
PATH_PARQUET_DIRECTORY = "datasets/raw/parquet"

DATABASE_TYPES = [
    "Cnaes",
    "Empresas",
    "Estabelecimentos",
    "Motivos",
    "Municipios",
    "Naturezas",
    "Paises",
    "Qualificacoes",
    "Simples",
    "Socios",
]

# https://deepnote.com/@regis-silva/Processo-ETL-DCC-64f1c42e-b666-4be4-83b5-8068f5d55747
DATABASE_COLUMNS = {
    "Cnaes": None,
    "Empresas": [
        "cnpj_base",
        "razao_social",
        "natureza_juridica",
        "qualificacao",
        "capital_social",
        "porte_empresa",
        "ente_federativo",
    ],
    "Estabelecimentos": [
        "cnpj_base",
        "cnpj_ordem",
        "cnpj_dv",
        "cd_matriz_filial",
        "nome_fantasia",
        "cd_situacao_cadastral",
        "dt_situacao_cadastral",
        "cd_motivo_situacao_cadastral",
        "cidade_exterior",
        "cd_pais",
        "dt_inicio_atividade",
        "cd_cnae_principal",
        "cd_cnae_secundario",
        "tipo_logradouro",
        "logradouro",
        "numero",
        "complemento",
        "bairro",
        "cep",
        "uf",
        "cd_municipio",
        "ddd1",
        "telefone1",
        "ddd2",
        "telefone2",
        "ddd_fax",
        "fax",
        "email",
        "situacao_especial",
        "dt_situacao_especial",
    ],
    "Motivos": None,
    "Municipios": None,
    "Naturezas": None,
    "Paises": None,
    "Qualificacoes": None,
    "Simples": None,
    "Socios": None,
}
